name: "Build"

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "pcov"
          php-version: "8.0"
          ini-values: memory_limit=-1

      - name: "Cache Composer dependencies"
        uses: actions/cache@v3
        with:
          path: |
            ~/.composer/cache
            vendor
          key: "php-8.0"
          restore-keys: "php-8.0"

      - name: "Validate composer"
        run: "composer validate"

      - name: "Install dependencies"
        run: "composer install"

      - name: "Run composer build"
        run: "composer build"
